package com.backtester.ui.javafx;

import com.backtester.config.AppConfig;
import com.backtester.config.EaParameter;
import com.backtester.config.EaParameterManager;
import com.backtester.report.OptimizationResult.CombinedPass;
import com.backtester.report.PassPresetResolver;
import com.backtester.workflow.CustomProject;
import javafx.beans.property.SimpleStringProperty;
import javafx.collections.FXCollections;
import javafx.collections.transformation.FilteredList;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.input.Clipboard;
import javafx.scene.input.ClipboardContent;
import javafx.scene.layout.*;
import javafx.scene.paint.Color;
import javafx.scene.text.Font;
import javafx.scene.text.FontWeight;
import javafx.stage.FileChooser;
import javafx.stage.Modality;
import javafx.stage.Stage;
import javafx.stage.Window;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.*;

/**
 * Helper component for displaying and downloading strategy .set files in JavaFX UI.
 *
 * <p>All parameter reconstruction is delegated to {@link PassPresetResolver}, which
 * honours the MT5 rules that make a naive rebuild wrong: optimized parameters take
 * their value from the optimize start, and inputs missing from the report may only
 * come from a preset archived with the run — never from the current EA config.
 */
public class SetfileDialogHelper {
    private static final Logger log = LoggerFactory.getLogger(SetfileDialogHelper.class);

    private static String expertOf(CombinedPass pass, CustomProject project) {
        if (project != null && project.getExpert() != null && !project.getExpert().isBlank()) {
            return project.getExpert();
        }
        return AppConfig.getInstance().get("app.expert", "");
    }

    /**
     * Returns the preset of a single concrete MT5 run, which may be used
     * byte-for-byte. Returns {@code null} for optimization runs: their archived
     * preset describes the whole search space, not this pass.
     */
    public static Path resolveExactPresetSource(CombinedPass combinedPass) {
        if (combinedPass == null) return null;
        for (String dir : new String[]{
                combinedPass.getReportDirectory(),
                combinedPass.getLongtermPass() != null ? combinedPass.getLongtermPass().getReportDirectory() : null,
                combinedPass.getBacktestPass() != null ? combinedPass.getBacktestPass().getReportDirectory() : null}) {
            PassPresetResolver.Snapshot snapshot = PassPresetResolver.findSnapshot(dir);
            if (snapshot != null && !snapshot.fromOptimization()) {
                return snapshot.presetFile();
            }
        }
        return null;
    }

    public static PassPresetResolver.Resolution resolvePassPreset(CombinedPass combinedPass, CustomProject project) {
        return PassPresetResolver.resolve(combinedPass, expertOf(combinedPass, project));
    }

    public static List<EaParameter> buildPassParameters(CombinedPass combinedPass, CustomProject project) {
        if (combinedPass == null) return Collections.emptyList();
        return resolvePassPreset(combinedPass, project).parameters();
    }

    public static String generateSetfileText(CombinedPass pass, CustomProject project) {
        Path exactPreset = resolveExactPresetSource(pass);
        if (exactPreset != null) {
            try {
                return Files.readString(exactPreset, StandardCharsets.UTF_16LE);
            } catch (Exception e) {
                try {
                    return Files.readString(exactPreset, StandardCharsets.UTF_8);
                } catch (Exception ignored) {}
            }
        }

        List<EaParameter> params = buildPassParameters(pass, project);
        StringBuilder sb = new StringBuilder();
        sb.append("; Setfile generated by MT5 Backtester\n");
        sb.append("; Strategy: ").append(pass.getStrategyName()).append(" (Pass #").append(pass.getPassNumber()).append(")\n");
        double profit = pass.getLongtermPass() != null ? pass.getLongtermPass().getProfit() : pass.getBtProfit();
        sb.append(String.format(Locale.US, "; Score: %.1f | Profit: $%.2f | BT Trades: %d\n", pass.getScore(), profit, pass.getBtTrades()));
        sb.append("; Date: ").append(java.time.LocalDateTime.now().format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))).append("\n;\n");

        String lastSection = "";
        for (EaParameter param : params) {
            if (param.getSection() != null && !param.getSection().isEmpty() && !param.getSection().equals(lastSection)) {
                lastSection = param.getSection();
                sb.append("; === ").append(lastSection).append(" ===\n");
            }
            sb.append(param.toSetFileLine()).append("\n");
        }
        return sb.toString();
    }

    public static void showSetfileViewDialog(CombinedPass pass, CustomProject project, Window owner) {
        if (pass == null) return;
        PassPresetResolver.Resolution resolution = resolvePassPreset(pass, project);
        List<EaParameter> allParams = resolution.parameters();
        String setfileText = generateSetfileText(pass, project);

        Stage stage = new Stage();
        stage.initModality(Modality.APPLICATION_MODAL);
        if (owner != null) stage.initOwner(owner);
        stage.setTitle("Setfile-Anzeige: " + pass.getStrategyName() + " (Pass #" + pass.getPassNumber() + ")");

        VBox root = new VBox(15);
        root.setPadding(new Insets(15));
        root.setStyle("-fx-background-color: #0b0d13;");
        root.setPrefSize(880, 620);

        // Header Row
        HBox header = new HBox(12);
        header.setAlignment(Pos.CENTER_LEFT);
        Label titleLbl = new Label("Setfile Parameter: " + pass.getStrategyName());
        titleLbl.setFont(Font.font("Segoe UI", FontWeight.BOLD, 18));
        titleLbl.setTextFill(Color.web("#00e5ff"));

        Label passBadge = new Label("Pass #" + pass.getPassNumber());
        passBadge.setStyle("-fx-background-color: #1e2432; -fx-text-fill: #ffd740; -fx-font-weight: bold; -fx-padding: 4 10 4 10; -fx-background-radius: 4;");

        Label paramCountBadge = new Label(allParams.size() + " Parameter");
        paramCountBadge.setStyle("-fx-background-color: #1e2432; -fx-text-fill: #10b981; -fx-font-weight: bold; -fx-padding: 4 10 4 10; -fx-background-radius: 4;");

        header.getChildren().addAll(titleLbl, passBadge, paramCountBadge, createFidelityBadge(resolution));

        TabPane tabPane = new TabPane();
        VBox.setVgrow(tabPane, Priority.ALWAYS);

        // TAB 1: Structured Table View
        Tab tableTab = new Tab("📊 Parameter-Tabelle (Übersichtlich)");
        tableTab.setClosable(false);

        VBox tableContent = new VBox(10);
        tableContent.setPadding(new Insets(10));

        // Filter / Search Box
        HBox filterBox = new HBox(10);
        filterBox.setAlignment(Pos.CENTER_LEFT);
        Label filterLabel = new Label("🔍 Suche:");
        filterLabel.setStyle("-fx-text-fill: #94a3b8; -fx-font-weight: bold;");

        TextField filterField = new TextField();
        filterField.setPromptText("Parameter-Name, Wert oder Sektion durchsuchen...");
        filterField.setStyle("-fx-background-color: #141822; -fx-text-fill: #00e5ff; -fx-border-color: #232a3b; -fx-border-radius: 4;");
        HBox.setHgrow(filterField, Priority.ALWAYS);

        filterBox.getChildren().addAll(filterLabel, filterField);

        TableView<EaParameter> table = new TableView<>();
        table.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY);
        table.setStyle("-fx-background-color: #141822; -fx-control-inner-background: #141822; -fx-table-cell-border-color: #232a3b;");

        TableColumn<EaParameter, String> sectionCol = new TableColumn<>("Sektion / Gruppe");
        sectionCol.setCellValueFactory(c -> new SimpleStringProperty(
                c.getValue().getSection() != null && !c.getValue().getSection().isEmpty() ? c.getValue().getSection() : "ALLGEMEIN"));
        sectionCol.setPrefWidth(160);
        sectionCol.setStyle("-fx-text-fill: #94a3b8; -fx-font-weight: bold;");

        TableColumn<EaParameter, String> nameCol = new TableColumn<>("Parameter Name");
        nameCol.setCellValueFactory(c -> new SimpleStringProperty(c.getValue().getName()));
        nameCol.setPrefWidth(240);
        nameCol.setStyle("-fx-text-fill: #00e5ff; -fx-font-family: 'Consolas';");

        TableColumn<EaParameter, String> valueCol = new TableColumn<>("Wert (Pass)");
        valueCol.setCellValueFactory(c -> new SimpleStringProperty(c.getValue().getValue()));
        valueCol.setPrefWidth(180);
        valueCol.setStyle("-fx-text-fill: #ffd740; -fx-font-weight: bold; -fx-font-family: 'Consolas';");

        TableColumn<EaParameter, String> optRangeCol = new TableColumn<>("Suchbereich (Start || Step || Ende)");
        optRangeCol.setCellValueFactory(c -> {
            EaParameter p = c.getValue();
            if (p.isStringType() || (p.getOptimizeStart().isEmpty() && p.getOptimizeEnd().isEmpty())) {
                return new SimpleStringProperty("-");
            }
            return new SimpleStringProperty(p.getOptimizeStart() + " || " + p.getOptimizeStep() + " || " + p.getOptimizeEnd());
        });
        optRangeCol.setPrefWidth(220);
        optRangeCol.setStyle("-fx-text-fill: #94a3b8; -fx-font-family: 'Consolas';");

        table.getColumns().addAll(sectionCol, nameCol, valueCol, optRangeCol);

        FilteredList<EaParameter> filteredParams = new FilteredList<>(FXCollections.observableArrayList(allParams), p -> true);
        filterField.textProperty().addListener((obs, oldVal, newVal) -> {
            String filter = newVal == null ? "" : newVal.trim().toLowerCase();
            filteredParams.setPredicate(p -> {
                if (filter.isEmpty()) return true;
                boolean nameMatch = p.getName() != null && p.getName().toLowerCase().contains(filter);
                boolean valMatch = p.getValue() != null && p.getValue().toLowerCase().contains(filter);
                boolean secMatch = p.getSection() != null && p.getSection().toLowerCase().contains(filter);
                return nameMatch || valMatch || secMatch;
            });
        });
        table.setItems(filteredParams);
        VBox.setVgrow(table, Priority.ALWAYS);

        tableContent.getChildren().addAll(filterBox, table);
        tableTab.setContent(tableContent);

        // TAB 2: Raw Text View
        Tab textTab = new Tab("📄 Raw .set-Datei (Export Format)");
        textTab.setClosable(false);

        TextArea textArea = new TextArea(setfileText);
        textArea.setFont(Font.font("Consolas", 13));
        textArea.setEditable(false);
        textArea.setStyle("-fx-control-inner-background: #141822; -fx-text-fill: #00e5ff; -fx-border-color: #232a3b;");
        VBox.setVgrow(textArea, Priority.ALWAYS);

        VBox textContent = new VBox(10);
        textContent.setPadding(new Insets(10));
        textContent.getChildren().add(textArea);
        textTab.setContent(textContent);

        tabPane.getTabs().addAll(tableTab, textTab);

        // Bottom Action Bar
        HBox buttonBar = new HBox(10);
        buttonBar.setAlignment(Pos.CENTER_RIGHT);

        Button copyBtn = new Button("In Zwischenablage kopieren");
        copyBtn.setStyle("-fx-background-color: #1e293b; -fx-text-fill: #00e5ff; -fx-border-color: #00e5ff; -fx-border-radius: 4; -fx-cursor: hand; -fx-font-weight: bold; -fx-padding: 6 12;");
        copyBtn.setOnAction(e -> {
            ClipboardContent content = new ClipboardContent();
            content.putString(setfileText);
            Clipboard.getSystemClipboard().setContent(content);
            copyBtn.setText("✓ Kopiert!");
        });

        Button downloadBtn = new Button("💾 Setfile download...");
        downloadBtn.setStyle("-fx-background-color: #1e293b; -fx-text-fill: #10b981; -fx-border-color: #10b981; -fx-border-radius: 4; -fx-cursor: hand; -fx-font-weight: bold; -fx-padding: 6 12;");
        downloadBtn.setOnAction(e -> {
            downloadSetfile(pass, project, owner != null ? owner : stage);
        });

        Button closeBtn = new Button("Schließen");
        closeBtn.setStyle("-fx-background-color: #2e3545; -fx-text-fill: white; -fx-cursor: hand; -fx-padding: 6 12;");
        closeBtn.setOnAction(e -> stage.close());

        buttonBar.getChildren().addAll(copyBtn, downloadBtn, closeBtn);

        root.getChildren().add(header);
        if (resolution.warning() != null) {
            Label warnLbl = new Label("⚠ " + resolution.warning());
            warnLbl.setWrapText(true);
            warnLbl.setStyle("-fx-background-color: #3a2a12; -fx-text-fill: #ffb74d; -fx-padding: 8 12 8 12; "
                    + "-fx-background-radius: 4; -fx-border-color: #ffb74d; -fx-border-radius: 4;");
            root.getChildren().add(warnLbl);
        }
        root.getChildren().addAll(tabPane, buttonBar);

        Scene scene = new Scene(root);
        if (owner != null && owner.getScene() != null && !owner.getScene().getStylesheets().isEmpty()) {
            scene.getStylesheets().addAll(owner.getScene().getStylesheets());
        }
        stage.setScene(scene);
        stage.show();
    }

    private static Label createFidelityBadge(PassPresetResolver.Resolution resolution) {
        String text;
        String color;
        switch (resolution.fidelity()) {
            case EXACT_SNAPSHOT -> {
                text = "✓ Original-Preset des Laufs";
                color = "#10b981";
            }
            case OPTIMIZATION_BASE -> {
                text = "✓ Optimierungs-Preset + Report-Werte";
                color = "#00e5ff";
            }
            default -> {
                text = "⚠ teilweise aus aktueller EA-Konfiguration";
                color = "#ffb74d";
            }
        }
        Label badge = new Label(text);
        badge.setStyle("-fx-background-color: #1e2432; -fx-text-fill: " + color
                + "; -fx-font-weight: bold; -fx-padding: 4 10 4 10; -fx-background-radius: 4;");
        if (resolution.source() != null) {
            badge.setTooltip(new Tooltip(resolution.source().toString()));
        }
        return badge;
    }

    public static void downloadSetfile(CombinedPass pass, CustomProject project, Window owner) {
        if (pass == null) return;
        FileChooser fileChooser = new FileChooser();
        fileChooser.setTitle("Setfile speichern");
        String safeName = pass.getStrategyName().replaceAll("[^a-zA-Z0-9_-]", "_");
        fileChooser.setInitialFileName(safeName + "_Pass" + pass.getPassNumber() + ".set");
        fileChooser.getExtensionFilters().add(new FileChooser.ExtensionFilter("MetaTrader Setfile (*.set)", "*.set"));

        File file = fileChooser.showSaveDialog(owner);
        if (file != null) {
            try {
                Path setPath = file.toPath();
                Path exactPreset = resolveExactPresetSource(pass);
                PassPresetResolver.Resolution resolution = null;
                if (exactPreset != null) {
                    Files.copy(exactPreset, setPath, StandardCopyOption.REPLACE_EXISTING);
                    log.info("Directly copied exact backtest preset snapshot to: {}", setPath);
                } else {
                    resolution = resolvePassPreset(pass, project);
                    new EaParameterManager().writeSetFile(setPath, resolution.parameters(),
                            expertOf(pass, project));
                }

                String message = "Setfile erfolgreich gespeichert:\n" + setPath.toAbsolutePath();
                if (resolution != null && resolution.warning() != null) {
                    message += "\n\n⚠ " + resolution.warning();
                }
                Alert alert = new Alert(Alert.AlertType.INFORMATION, message, ButtonType.OK);
                if (owner != null) alert.initOwner(owner);
                alert.setTitle("Setfile Download");
                alert.setHeaderText("Setfile gespeichert");
                alert.showAndWait();
            } catch (Exception ex) {
                log.error("Failed to save setfile", ex);
                Alert alert = new Alert(Alert.AlertType.ERROR, "Fehler beim Speichern der Set-Datei:\n" + ex.getMessage(), ButtonType.OK);
                if (owner != null) alert.initOwner(owner);
                alert.showAndWait();
            }
        }
    }
}
