#MT5 Backtester Configuration
#Sun Apr 05 18:31:51 CEST 2026
backtest.currency=USD
backtest.deposit=10000
backtest.leverage=1\:100
backtest.model=1
broker.timezone.offset=2
data.directory=D\:\\AntiGravitySoftware\\GitWorkspace\\Backtester\\data
mt5.portable.mode=true
mt5.terminal.path=C\:\\Forex\\Mt5\\TickmillLifeMql5\\terminal64.exe
output.directory=D\:\\AntiGravitySoftware\\GitWorkspace\\Backtester\\backtest_reports
