#MT5 Backtester Configuration
#Wed Apr 08 10:52:24 CEST 2026
backtest.currency=USD
backtest.dateFrom=2022-04-07
backtest.dateTo=2026-04-07
backtest.deposit=10000
backtest.expert=ToTheMoon 3.5 MT5 English (2)
backtest.leverage=1\:100
backtest.model=1
backtest.period=M5
backtest.symbol=AUDCAD
broker.timezone.offset=2
data.directory=D\:\\AntiGravitySoftware\\GitWorkspace\\Backtester\\data
mt5.portable.mode=true
mt5.terminal.path=C\:\\Forex\\Mt5\\TickmillLifeMql5\\terminal64.exe
output.directory=D\:\\AntiGravitySoftware\\GitWorkspace\\Backtester\\backtest_reports
robustness.currency=USD
robustness.dateFrom=2025-04-07
robustness.dateTo=2026-04-07
robustness.deposit=10000
robustness.expert=ToTheMoon 3.5 MT5 English (2)
robustness.leverage=1\:100
robustness.metric=0
robustness.model=1
robustness.period=M5
robustness.shiftdays=90
robustness.shifts=0
robustness.symbol=AUDCAD
