#MT5 Backtester Configuration
#Sat May 02 16:09:31 CEST 2026
backtest.currency=USD
backtest.dateFrom=2025-10-07
backtest.dateTo=2026-04-07
backtest.deposit=10000
backtest.expert=Market\\Scalper Deriv
backtest.leverage=1\:100
backtest.model=1 minute OHLC
backtest.period=H1
backtest.symbol=USDJPY
broker.timezone.offset=2
data.directory=D\:\\AntiGravitySoftware\\GitWorkspace\\Backtester\\data
mt5.portable.mode=true
mt5.terminal.path=C\:\\Forex\\Mt5\\TickmillLifeMql5\\terminal64.exe
multi.deposit=10000
multi.experts=Market\\Scalper Deriv
multi.from=2025-04-26
multi.symbols=EURUSD
multi.tickmodel=1
multi.timeframes=H1
multi.to=2026-04-26
multibacktest.expert=Market\\Scalper Deriv
multibacktest.model=1 minute OHLC
multibacktest.symbol=EURUSD,USDJPY
multibacktest.timeframes=H1
optimization.criterion=Recovery Factor max
optimization.expert=Market\\Scalper Deriv
optimization.forwardMode=1/2 period
optimization.fromDate=2026-01-01
optimization.mode=Fast Genetic Algorithm
optimization.model=1 minute OHLC
optimization.period=H1
optimization.symbol=XAUUSD
optimization.toDate=2026-04-26
output.directory=D\:\\AntiGravitySoftware\\GitWorkspace\\Backtester\\backtest_reports
robustness.currency=USD
robustness.dateFrom=2025-04-07
robustness.dateTo=2026-04-07
robustness.deposit=10000
robustness.expert=Market\\Scalper Deriv
robustness.leverage=1\:100
robustness.metric=Balance max
robustness.model=1 minute OHLC
robustness.period=H1
robustness.shiftdays=360
robustness.shifts=3
robustness.symbol=EURUSD
