//+------------------------------------------------------------------+
//| DukaImporter.mq5 - CSV Data Importer for Custom Symbols          |
//| Imports M1 OHLCV data from CSV into MT5 Custom Symbols           |
//| Generated by MT5 Backtester                                       |
//+------------------------------------------------------------------+
#property copyright "MT5 Backtester"
#property link      "https://github.com/antigravity"
#property version   "1.00"
#property script_show_inputs

input string InpCustomName = "EURUSD_Duka";     // Custom Symbol Name
input string InpOriginName = "EURUSD";           // Base Symbol (for properties)
input string InpCsvFile    = "EURUSD_M1.csv";   // CSV File Name (in MQL5/Files/)
input int    InpDigits     = 5;                   // Price Digits

//+------------------------------------------------------------------+
void OnStart()
{
    Print("=== DukaImporter Start ===");
    Print("Custom Symbol: ", InpCustomName);
    Print("Origin Symbol: ", InpOriginName);
    Print("CSV File: ", InpCsvFile);
    Print("Digits: ", InpDigits);
    
    // Step 1: Create Custom Symbol
    if(!CustomSymbolCreate(InpCustomName, "CustomData\\" + InpOriginName, InpOriginName))
    {
        int err = GetLastError();
        if(err != 5304) // 5304 = symbol already exists
        {
            Print("ERROR: Cannot create symbol ", InpCustomName, " Error: ", err);
            return;
        }
        Print("Custom symbol already exists: ", InpCustomName);
    }
    else
    {
        Print("Custom symbol created: ", InpCustomName);
    }
    
    // Step 2: Set symbol properties
    CustomSymbolSetInteger(InpCustomName, SYMBOL_DIGITS, InpDigits);
    CustomSymbolSetInteger(InpCustomName, SYMBOL_CHART_MODE, SYMBOL_CHART_MODE_BID);
    CustomSymbolSetInteger(InpCustomName, SYMBOL_TRADE_EXEMODE, SYMBOL_TRADE_EXECUTION_MARKET);
    CustomSymbolSetInteger(InpCustomName, SYMBOL_TRADE_CALC_MODE, SYMBOL_CALC_MODE_FOREX);
    CustomSymbolSetDouble(InpCustomName, SYMBOL_POINT, MathPow(10, -InpDigits));
    CustomSymbolSetDouble(InpCustomName, SYMBOL_TRADE_TICK_SIZE, MathPow(10, -InpDigits));
    CustomSymbolSetDouble(InpCustomName, SYMBOL_TRADE_TICK_VALUE, 1.0);
    CustomSymbolSetDouble(InpCustomName, SYMBOL_TRADE_CONTRACT_SIZE, 100000);
    CustomSymbolSetDouble(InpCustomName, SYMBOL_VOLUME_MIN, 0.01);
    CustomSymbolSetDouble(InpCustomName, SYMBOL_VOLUME_MAX, 100.0);
    CustomSymbolSetDouble(InpCustomName, SYMBOL_VOLUME_STEP, 0.01);
    Print("Symbol properties configured");
    
    // Step 3: Read CSV file
    int fileHandle = FileOpen(InpCsvFile, FILE_READ|FILE_CSV|FILE_ANSI, ',');
    if(fileHandle == INVALID_HANDLE)
    {
        Print("ERROR: Cannot open file ", InpCsvFile, " Error: ", GetLastError());
        return;
    }
    
    // Skip header line
    if(!FileIsEnding(fileHandle))
    {
        while(!FileIsLineEnding(fileHandle) && !FileIsEnding(fileHandle))
        {
            FileReadString(fileHandle);
        }
    }
    
    // Step 4: Read data into MqlRates array
    MqlRates rates[];
    int count = 0;
    int batchSize = 100000;
    ArrayResize(rates, batchSize);
    
    while(!FileIsEnding(fileHandle))
    {
        if(count >= ArraySize(rates))
            ArrayResize(rates, ArraySize(rates) + batchSize);
        
        string dateStr  = FileReadString(fileHandle);   // Date: YYYY.MM.DD
        string timeStr  = FileReadString(fileHandle);   // Time: HH:MM
        double openVal  = FileReadNumber(fileHandle);    // Open
        double highVal  = FileReadNumber(fileHandle);    // High
        double lowVal   = FileReadNumber(fileHandle);    // Low
        double closeVal = FileReadNumber(fileHandle);    // Close
        long   tickVol  = (long)FileReadNumber(fileHandle);  // TickVolume
        long   volume   = (long)FileReadNumber(fileHandle);  // Volume
        int    spread   = (int)FileReadNumber(fileHandle);   // Spread
        
        if(StringLen(dateStr) < 8) continue;
        
        // Parse datetime
        string dtStr = dateStr + " " + timeStr;
        datetime dt = StringToTime(dtStr);
        
        if(dt <= 0) continue;
        
        rates[count].time       = dt;
        rates[count].open       = NormalizeDouble(openVal, InpDigits);
        rates[count].high       = NormalizeDouble(highVal, InpDigits);
        rates[count].low        = NormalizeDouble(lowVal, InpDigits);
        rates[count].close      = NormalizeDouble(closeVal, InpDigits);
        rates[count].tick_volume = tickVol;
        rates[count].real_volume = volume;
        rates[count].spread     = spread;
        
        count++;
        
        // Progress update every 100k bars
        if(count % 100000 == 0)
            Print("Read ", count, " bars...");
    }
    
    FileClose(fileHandle);
    
    if(count == 0)
    {
        Print("ERROR: No valid data read from CSV");
        return;
    }
    
    ArrayResize(rates, count);
    Print("Total bars read from CSV: ", count);
    
    // Step 5: Import data using CustomRatesReplace
    // This overwrites existing data in the specified time range
    Print("Importing data (this may take a moment)...");
    int replaced = CustomRatesReplace(InpCustomName, rates[0].time, rates[count-1].time, rates);
    
    if(replaced > 0)
    {
        Print("SUCCESS: Imported ", replaced, " bars into ", InpCustomName);
        Print("Data range: ", TimeToString(rates[0].time), " - ", TimeToString(rates[count-1].time));
    }
    else
    {
        Print("ERROR: CustomRatesReplace failed. Error: ", GetLastError());
    }
    
    // Step 6: Enable symbol in Market Watch
    SymbolSelect(InpCustomName, true);
    Print("Symbol ", InpCustomName, " added to Market Watch");
    
    Print("=== DukaImporter Complete ===");
}
